// <auto-generated />
using System;
using CurriculumWebAPI.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurriculumWebAPI.Infrastructure.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230606044737_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("MyPortfolio.CurriculumWebAPI.Models.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienciaProfissional")
                        .HasColumnType("TEXT");

                    b.Property<string>("Habilidades")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SobreMim")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curriculum");
                });

            modelBuilder.Entity("MyPortfolio.CurriculumWebAPI.Models.Educacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoConclusao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instituicao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Educacao");
                });

            modelBuilder.Entity("MyPortfolio.CurriculumWebAPI.Models.Educacao", b =>
                {
                    b.HasOne("MyPortfolio.CurriculumWebAPI.Models.Curriculum", null)
                        .WithMany("Educacao")
                        .HasForeignKey("CurriculumId");
                });

            modelBuilder.Entity("MyPortfolio.CurriculumWebAPI.Models.Curriculum", b =>
                {
                    b.Navigation("Educacao");
                });
#pragma warning restore 612, 618
        }
    }
}
