name: Deploy


on:
  push:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/paulo/Apps/MyPortfolio
          git pull origin master
          git status
          cd /home/paulo/Apps/MyPortfolio/MyPortfolio.CurriculumWebAPI
          dotnet build
          cd /home/paulo/Apps/MyPortfolio/MyPortfolio.CurriculumWebAPI/bin/Debug/net6.0
          dotnet CurriculumWebAPI.App.dll
          screen -dmS api-screen dotnet CurriculumWebAPI.App.dll
          screen -d -r api-screen