name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/paulo/Apps/MyPortfolio
          git pull origin master
          git status
          cd /home/paulo/Apps/MyPortfolio/MyPortfolio.CurriculumWebAPI

          if screen -list | grep -q "api-screen"; then

            screen -S api-screen -X stuff "^C"
            sleep 2 
          fi

          dotnet build
          screen -dmS api-screen
          screen -S api-screen -X stuff "dotnet run$(echo -ne '\r')"
